#!/bin/bash

version=1.0.0
app=sd_agent
pidpath="/var/run"
pidname=sdagent.pid
pidfile=$pidpath/$pidname
binpath="/usr/bin/"$app
logpath="/var/log/agent.log"
confpath="/etc/sdconfig.json"
dns="etcd.product.sdp.nd"

check_pid(){
	if [ -f $pidfile ];then
        	pid=`cat $pidfile`
        	if [ -n $pid ]; then
			running=`ps -p $pid|grep -v "PID TTY" |wc -l`
            		return $running
		fi
    	fi
	return 0
}

stop(){
        pid=`cat $pidfile`
    	kill $pid
    	echo "$app stoped..."
}

start(){
	check_pid
	running=$?
	if [ $running -gt 0 ];then
		echo -n "$app now is running already,pid ="
		cat $pidfile
		return 1
	fi
		
        if ! [ -f $confpath ];then
		echo "config file $confpath doesn't exist"
		return 1
	fi
		
	if [ ! -e $binpath ];then
        	echo "excution file is not exist in /usr/bin/$app"
       	 	return 1
	fi
		
        $binpath -d=$dns -f=$confpath -m=$pidpath >>$logpath 2>&1 &
	sleep 1
	echo "$app started.., pid = $!"
}

restart(){
        stop
	sleep 1
        start
}

status() {
    	check_pid
    	running=$?
    	if [ $running -gt 0 ];then
        	echo started
   	else
        	echo stoped
    	fi
}

version(){
	echo $version
}


tailf() {
	tail -f $logpath
}

install(){
	cp sdagent /etc/init.d/
	cp agent /usr/bin/$app
		
	if [ ! -e /etc/init.d/sdagent ];then
       		echo "sdagent install fail, can't copy sdagent"
        	return 1
	fi

	if [ ! -e /usr/bin/$app ];then
	        echo "sdagent install fail, can't copy agent"
	        return 1
	fi
	echo "install sdagent success."
	return 0
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
restart)
        restart
        ;;
status)
	status
	;;
tail)
	tailf
	;;
install)
	install
	;;
version)
	version
	;;
*)
        echo "use start/stop/restart/status/tail/version/install"
        exit 1
esac
